### ISSUE TITLE
/usr/bin/startup.sh: 44: exec: ipexrun: not found

### ISSUE THREAD

**Issue by ksullivan86** [simonlui/Docker_IPEX_ComfyUI#12]
I am trying to run from a compose file but I am a little confused about what I am missing.

I am guessing its something with the environment variables in my compose.yaml but I am not sure what to use to get this to work? I should note I am able to use sdnext with the GPU a770 so I dont think its a GPU passthrough issue.

Here is the end of the logs from starting the container:

```
Installing collected packages: triton, trampoline, sentencepiece, nvidia-cusparselt-cu12, mpmath, urllib3, typing-extensions, tqdm, sympy, safetensors, regex, pyyaml, pycparser, psutil, propcache, Pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, multidict, MarkupSafe, kornia_rs, idna, fsspec, frozenlist, filelock, einops, comfyui-frontend-package, charset-normalizer, certifi, av, attrs, aiohappyeyeballs, yarl, scipy, requests, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jinja2, cffi, aiosignal, soundfile, nvidia-cusolver-cu12, huggingface-hub, aiohttp, torch, tokenizers, transformers, torchvision, torchsde, torchaudio, kornia, spandrel

Successfully installed MarkupSafe-3.0.2 Pillow-11.1.0 aiohappyeyeballs-2.6.1 aiohttp-3.11.16 aiosignal-1.3.2 attrs-25.3.0 av-14.2.0 certifi-2025.1.31 cffi-1.17.1 charset-normalizer-3.4.1 comfyui-frontend-package-1.14.6 einops-0.8.1 filelock-3.18.0 frozenlist-1.5.0 fsspec-2025.3.2 huggingface-hub-0.30.1 idna-3.10 jinja2-3.1.6 kornia-0.8.0 kornia_rs-0.1.8 mpmath-1.3.0 multidict-6.3.2 networkx-3.4.2 numpy-2.2.4 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 propcache-0.3.1 psutil-7.0.0 pycparser-2.22 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.5.3 scipy-1.15.2 sentencepiece-0.2.0 soundfile-0.13.1 spandrel-0.4.1 sympy-1.13.1 tokenizers-0.21.1 torch-2.6.0 torchaudio-2.6.0 torchsde-0.2.6 torchvision-0.21.0 tqdm-4.67.1 trampoline-0.1.2 transformers-4.50.3 triton-3.2.0 typing-extensions-4.13.1 urllib3-2.3.0 yarl-1.18.3

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Using ipexrun xpu to launch ComfyUI.

/usr/bin/startup.sh: 44: exec: ipexrun: not found
```

This is my compose.yaml:

```
services:
 confyui-ipex:
    build:
      context: ./install-files
      dockerfile: Dockerfile
    container_name: confyui-ipex
    image: confyui-ipex:latest
    security_opt:
      - label=disable 
    ports:
      - 8188:8188
    devices:
      - /dev/dri:/dev/dri
    environment:
      - ComfyArgs="<ComfyUI command line arguments>"
      - IPEXRUNArgs=true
      - UseIPEXRUN=true
    volumes:
      - /mnt/unraid/ai/appdata/stable_diffusion/confyui-ipex/ComfyUI:/ComfyUI:Z
      - /mnt/unraid/ai/stable_diffusion/deps:/deps
      - /mnt/unraid/ai/stable_diffusion/models:/models
      - /mnt/unraid/ai/stable_diffusion/huggingface:/root/.cache/huggingface
```
